# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160511_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='untitled', max_length=400),
            preserve_default=False,
        ),
    ]
